//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibrarySystemEntities2 : DbContext
    {
        public LibrarySystemEntities2()
            : base("name=LibrarySystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Borrower> Borrowers { get; set; }
        public virtual DbSet<HeadLibrarian> HeadLibrarians { get; set; }
        public virtual DbSet<Librarian> Librarians { get; set; }
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
    }
}
