//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public int Itemid { get; set; }
        public string ItemType { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Edition { get; set; }
        public string ISBNumber { get; set; }
        public string ItemStatus { get; set; }
        public string LibraianDetails { get; set; }
        public string StaffDetails { get; set; }
    }
}
