//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public Nullable<int> NumOfAvailableItems { get; set; }
        public Nullable<int> NumOfBorroersItems { get; set; }
        public Nullable<int> NumOfOverdueItems { get; set; }
        public Nullable<int> NumOfBorrowes { get; set; }
        public Nullable<int> NumOfStaff { get; set; }
    }
}
